# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Minxing Pang
title: Research Assistant
email: maxpmx@outlook.com
phone: +86 13622000965
# website: Your website (eg. https://google.com)(optional)

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: image/photo4.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a junior undergraduate student majoring in Applied Mathematics, interested in mathematics and computer science.

  My research/work interests are as followed
    - Architecture of Nerual Network 
    - Application of Deep Learning to Finance
    - Information and Numerical science
    - Mathematical Model

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Extracurricular Activities

  I am also Co-Chair of Nankai Quantitative Investment Club who enjoy cooperate with excellent people.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
